// docker/rule-engine/ui-angular/src/app/pages/rules.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ApiService, toApiError } from '../core/api.service';
import type { RuleView } from '../core/types';
import { load } from '../shared/resource';
import { ActionBadge, ErrorNotice, Field, Loading, PageHeader, ScopeBadge, StatusBadge } from '../shared/ui';

/** Every rule the caller may see, with its expression, messages, the parameters it reads and the groups that use it. */
@Component({
  selector: 'app-rules',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, PageHeader, ErrorNotice, Field, Loading, ActionBadge, ScopeBadge, StatusBadge],
  template: `
    <app-page-header title="Rules">
      A rule is one CEL expression with what to say and do when it is true or false. Rules are checked against the parameter
      library when they are saved.
      <span actions><a class="btn btn-primary" routerLink="/rules/new">New rule</a></span>
    </app-page-header>
    <div class="toolbar">
      <app-field controlId="rule-module" label="Module">
        <select id="rule-module" (change)="module.set($any($event.target).value); rules.reload()">
          <option value="">All modules</option>
          @for (m of modules.data() ?? []; track m.code) { <option [value]="m.code">{{ m.name }}</option> }
        </select>
      </app-field>
      <app-field controlId="rule-status" label="Status">
        <select id="rule-status" (change)="status.set($any($event.target).value); rules.reload()">
          <option value="">Any</option>
          <option value="ACTIVE">Active</option>
          <option value="DRAFT">Draft</option>
          <option value="RETIRED">Retired</option>
        </select>
      </app-field>
    </div>
    <app-error-notice [error]="actionError()" />
    <app-error-notice [error]="rules.error()" />
    @if (rules.loading() && !rules.data()) { <app-loading what="Loading rules" /> }
    @if (rules.data(); as list) {
      @if (list.length === 0) {
        <p class="empty">No rule matches. <a routerLink="/rules/new">Create one.</a></p>
      } @else {
        <div class="table-wrap">
          <table>
            <caption class="visually-hidden">Rules</caption>
            <thead><tr><th>Rule</th><th>Expression</th><th>If true</th><th>If false</th><th>Scope</th><th>Status</th></tr></thead>
            <tbody>
              @for (r of list; track r.id) {
                <tr class="clickable" (click)="toggle(r.id)">
                  <td>
                    <button type="button" class="btn-link" [attr.aria-expanded]="open() === r.id" (click)="$event.stopPropagation(); toggle(r.id)">{{ r.name }}</button>
                    <div class="hint mono">{{ r.moduleCode }} · {{ r.code }}</div>
                  </td>
                  <td><code>{{ r.expression }}</code></td>
                  <td><app-action [value]="r.trueAction" /></td>
                  <td><app-action [value]="r.falseAction" /></td>
                  <td><app-scope [value]="r.scope" /></td>
                  <td><app-status [value]="r.status" /></td>
                </tr>
                @if (open() === r.id) {
                  <tr>
                    <td colspan="6">
                      <div class="panel">
                        <dl class="kv">
                          <dt>Reads</dt>
                          <dd>@for (p of r.parameters; track p) { <code>{{ p }} </code> } @empty { — }</dd>
                          <dt>Used in groups</dt>
                          <dd>{{ r.groups.length ? r.groups.join(', ') : 'none yet' }}</dd>
                          <dt>Message if true</dt>
                          <dd>@for (t of entries(r.trueMessage); track t[0]) { <div><span class="badge">{{ t[0] }}</span> {{ t[1] }}</div> } @empty { silent }</dd>
                          <dt>Message if false</dt>
                          <dd>@for (t of entries(r.falseMessage); track t[0]) { <div><span class="badge">{{ t[0] }}</span> {{ t[1] }}</div> } @empty { silent }</dd>
                        </dl>
                        <div class="actions">
                          @if (r.status !== 'ACTIVE') { <button type="button" class="btn btn-small" (click)="change(r, 'ACTIVE')">Activate</button> }
                          @if (r.status === 'ACTIVE') { <button type="button" class="btn btn-small" (click)="change(r, 'DRAFT')">Move to draft</button> }
                          @if (r.status !== 'RETIRED') { <button type="button" class="btn btn-small btn-danger" (click)="change(r, 'RETIRED')">Retire</button> }
                        </div>
                      </div>
                    </td>
                  </tr>
                }
              }
            </tbody>
          </table>
        </div>
      }
    }
  `,
})
export class RulesPage {
  private readonly api = inject(ApiService);
  protected readonly module = signal('');
  protected readonly status = signal('');
  protected readonly open = signal<string | null>(null);
  protected readonly actionError = signal<unknown>(null);
  protected readonly modules = load(() => this.api.modules());
  protected readonly rules = load(() => this.api.rules(this.module() || undefined, this.status() || undefined));

  protected toggle(id: string): void {
    this.open.set(this.open() === id ? null : id);
  }

  protected entries(texts: Record<string, string>): Array<[string, string]> {
    return Object.entries(texts);
  }

  protected async change(rule: RuleView, next: string): Promise<void> {
    this.actionError.set(null);
    try {
      await this.api.setRuleStatus(rule.id, next);
      this.rules.reload();
    } catch (e) {
      this.actionError.set(toApiError(e));
    }
  }
}

// docker/rule-engine/ui/src/pages/Rules.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { engine } from '../api/engine';
import type { RuleView } from '../api/types';
import { ActionBadge, Async, ErrorNotice, Field, PageHeader, ScopeBadge, StatusBadge, useLoad } from '../components/ui';

/** Every rule the caller may see, with its expression, messages, the parameters it reads and the groups that use it. */
export function RulesPage() {
  const [module, setModule] = useState('');
  const [status, setStatus] = useState('');
  const [open, setOpen] = useState<string | null>(null);
  const [actionError, setActionError] = useState<unknown>(null);
  const modules = useLoad(engine.modules, []);
  const rules = useLoad(() => engine.rules(module || undefined, status || undefined), [module, status]);

  async function change(rule: RuleView, next: string) {
    setActionError(null);
    try {
      await engine.setRuleStatus(rule.id, next);
      rules.reload();
    } catch (e) {
      setActionError(e);
    }
  }

  return (
    <>
      <PageHeader
        title="Rules"
        actions={
          <Link className="btn btn-primary" to="/rules/new">
            New rule
          </Link>
        }
      >
        A rule is one CEL expression with what to say and do when it is true or false. Rules are checked against the parameter
        library when they are saved.
      </PageHeader>
      <div className="toolbar">
        <Field id="rule-module" label="Module">
          <select id="rule-module" value={module} onChange={(e) => setModule(e.target.value)}>
            <option value="">All modules</option>
            {modules.data?.map((m) => (
              <option key={m.code} value={m.code}>
                {m.name}
              </option>
            ))}
          </select>
        </Field>
        <Field id="rule-status" label="Status">
          <select id="rule-status" value={status} onChange={(e) => setStatus(e.target.value)}>
            <option value="">Any</option>
            <option value="ACTIVE">Active</option>
            <option value="DRAFT">Draft</option>
            <option value="RETIRED">Retired</option>
          </select>
        </Field>
      </div>
      <ErrorNotice error={actionError} />
      <Async load={rules} what="Loading rules">
        {(list) =>
          list.length === 0 ? (
            <p className="empty">
              No rule matches. <Link to="/rules/new">Create one.</Link>
            </p>
          ) : (
            <div className="table-wrap">
              <table>
                <caption className="visually-hidden">Rules</caption>
                <thead>
                  <tr>
                    <th>Rule</th>
                    <th>Expression</th>
                    <th>If true</th>
                    <th>If false</th>
                    <th>Scope</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {list.map((r) => (
                    <RuleRows key={r.id} rule={r} open={open === r.id} toggle={() => setOpen(open === r.id ? null : r.id)} change={change} />
                  ))}
                </tbody>
              </table>
            </div>
          )
        }
      </Async>
    </>
  );
}

function RuleRows(props: { rule: RuleView; open: boolean; toggle: () => void; change: (r: RuleView, status: string) => void }) {
  const r = props.rule;
  return (
    <>
      <tr className="clickable" onClick={props.toggle}>
        <td>
          <button className="btn-link" aria-expanded={props.open} onClick={(e) => { e.stopPropagation(); props.toggle(); }}>
            {r.name}
          </button>
          <div className="hint mono">
            {r.moduleCode} · {r.code}
          </div>
        </td>
        <td>
          <code>{r.expression}</code>
        </td>
        <td>
          <ActionBadge value={r.trueAction} />
        </td>
        <td>
          <ActionBadge value={r.falseAction} />
        </td>
        <td>
          <ScopeBadge value={r.scope} />
        </td>
        <td>
          <StatusBadge value={r.status} />
        </td>
      </tr>
      {props.open && (
        <tr>
          <td colSpan={6}>
            <div className="panel">
              <dl className="kv">
                <dt>Reads</dt>
                <dd>{r.parameters.length ? r.parameters.map((p) => <code key={p}>{p} </code>) : '—'}</dd>
                <dt>Used in groups</dt>
                <dd>{r.groups.length ? r.groups.join(', ') : 'none yet'}</dd>
                <dt>Message if true</dt>
                <dd>{Object.keys(r.trueMessage).length ? Object.entries(r.trueMessage).map(([l, t]) => <div key={l}><span className="badge">{l}</span> {t}</div>) : 'silent'}</dd>
                <dt>Message if false</dt>
                <dd>{Object.keys(r.falseMessage).length ? Object.entries(r.falseMessage).map(([l, t]) => <div key={l}><span className="badge">{l}</span> {t}</div>) : 'silent'}</dd>
              </dl>
              <div className="actions">
                {r.status !== 'ACTIVE' && (
                  <button className="btn btn-small" onClick={() => props.change(r, 'ACTIVE')}>
                    Activate
                  </button>
                )}
                {r.status === 'ACTIVE' && (
                  <button className="btn btn-small" onClick={() => props.change(r, 'DRAFT')}>
                    Move to draft
                  </button>
                )}
                {r.status !== 'RETIRED' && (
                  <button className="btn btn-small btn-danger" onClick={() => props.change(r, 'RETIRED')}>
                    Retire
                  </button>
                )}
              </div>
            </div>
          </td>
        </tr>
      )}
    </>
  );
}
