// docker/rule-engine/ui-angular/src/app/shared/texts-editor.ts
import { ChangeDetectionStrategy, Component, computed, input, model } from '@angular/core';
import type { Texts } from '../core/types';

const COMMON: Array<[string, string]> = [
  ['en', 'English'],
  ['hi', 'Hindi'],
  ['th', 'Thai'],
  ['pt-BR', 'Portuguese (Brazil)'],
  ['es', 'Spanish'],
  ['fr', 'French'],
  ['de', 'German'],
];

/** Drops blank rows (a language without text) before sending. */
export function cleanTexts(texts: Texts): Texts | undefined {
  const entries = Object.entries(texts)
    .map(([k, v]) => [k.trim(), v.trim()] as const)
    .filter(([k, v]) => k && v);
  return entries.length ? Object.fromEntries(entries) : undefined;
}

/**
 * One message in several languages: a row per language (tag + text). Empty rows are dropped by {@link cleanTexts}; the
 * service validates tags and length again, this is only for the experience.
 */
@Component({
  selector: 'app-texts-editor',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <fieldset class="field texts">
      <legend class="label">{{ label() }}</legend>
      @if (rows().length === 0) {
        <p class="hint">No message: this outcome stays silent.</p>
      }
      @for (row of rows(); track $index) {
        <div class="texts-row">
          <input type="text" [attr.aria-label]="label() + ': language ' + ($index + 1)" [value]="row[0]"
                 (change)="rename($index, $any($event.target).value)" />
          <input type="text" [attr.aria-label]="label() + ': text (' + row[0] + ')'" [value]="row[1]"
                 (input)="retext($index, $any($event.target).value)" />
          <button type="button" class="btn btn-small btn-danger" [attr.aria-label]="'Remove ' + row[0] + ' message'"
                  (click)="remove($index)">Remove</button>
        </div>
      }
      <div class="actions">
        @for (c of unused(); track c[0]) {
          <button type="button" class="btn btn-small" (click)="add(c[0])">+ {{ c[1] }}</button>
        }
      </div>
    </fieldset>
  `,
})
export class TextsEditor {
  readonly label = input.required<string>();
  readonly value = model.required<Texts>();

  protected readonly rows = computed(() => Object.entries(this.value()));
  protected readonly unused = computed(() => COMMON.filter(([tag]) => !(tag in this.value())).slice(0, 3));

  private set(next: Array<[string, string]>): void {
    this.value.set(Object.fromEntries(next));
  }

  protected rename(i: number, tag: string): void {
    this.set(this.rows().map(([t, x], j) => (j === i ? [tag.trim(), x] : [t, x])));
  }

  protected retext(i: number, text: string): void {
    this.set(this.rows().map(([t, x], j) => (j === i ? [t, text] : [t, x])));
  }

  protected remove(i: number): void {
    this.set(this.rows().filter((_, j) => j !== i));
  }

  protected add(tag: string): void {
    this.set([...this.rows(), [tag, '']]);
  }
}

// docker/rule-engine/ui/src/components/TextsEditor.tsx
import { useId } from 'react';
import type { Texts } from '../api/types';

const COMMON: Array<[string, string]> = [
  ['en', 'English'],
  ['hi', 'Hindi'],
  ['th', 'Thai'],
  ['pt-BR', 'Portuguese (Brazil)'],
  ['es', 'Spanish'],
  ['fr', 'French'],
  ['de', 'German'],
];

/**
 * One message in several languages: a row per language (tag + text). Empty rows are dropped by {@link cleanTexts}; the
 * service validates tags and length again, this is only for the experience.
 */
export function TextsEditor(props: { label: string; value: Texts; onChange: (v: Texts) => void; hint?: string }) {
  const id = useId();
  const rows = Object.entries(props.value);
  const set = (next: Array<[string, string]>) => props.onChange(Object.fromEntries(next));
  const unused = COMMON.filter(([tag]) => !(tag in props.value));
  return (
    <fieldset className="field" style={{ border: 0, padding: 0, margin: '0 0 var(--space-4)' }}>
      <legend className="label" style={{ fontSize: 'var(--text-sm)', fontWeight: 'var(--weight-medium)' }}>
        {props.label}
      </legend>
      {rows.length === 0 && <p className="hint">No message: this outcome stays silent.</p>}
      {rows.map(([tag, text], i) => (
        <div key={tag} style={{ display: 'grid', gridTemplateColumns: '6rem 1fr auto', gap: 'var(--space-2)' }}>
          <input
            type="text"
            aria-label={`${props.label}: language ${i + 1}`}
            value={tag}
            onChange={(e) => {
              const copy: Array<[string, string]> = rows.map((r) => [r[0], r[1]]);
              copy[i] = [e.target.value.trim(), text];
              set(copy);
            }}
          />
          <input
            type="text"
            aria-label={`${props.label}: text (${tag})`}
            value={text}
            onChange={(e) => set(rows.map(([t, x], j) => (j === i ? [t, e.target.value] : [t, x])))}
          />
          <button
            type="button"
            className="btn btn-small btn-danger"
            aria-label={`Remove ${tag} message`}
            onClick={() => set(rows.filter((_, j) => j !== i))}
          >
            Remove
          </button>
        </div>
      ))}
      <div className="actions" style={{ marginTop: 'var(--space-2)' }}>
        {unused.slice(0, 3).map(([tag, name]) => (
          <button
            key={tag}
            type="button"
            className="btn btn-small"
            id={`${id}-${tag}`}
            onClick={() => set([...rows, [tag, '']])}
          >
            + {name}
          </button>
        ))}
      </div>
      {props.hint && <span className="hint">{props.hint}</span>}
    </fieldset>
  );
}

/** Drops blank rows (a language without text) before sending. */
export function cleanTexts(texts: Texts): Texts | undefined {
  const entries = Object.entries(texts)
    .map(([k, v]) => [k.trim(), v.trim()] as const)
    .filter(([k, v]) => k && v);
  return entries.length ? Object.fromEntries(entries) : undefined;
}
